// 🏙️ Location and property constants
export const LOCATION_OPTIONS = {
  cities: [
    { id: 1, label: "آبادان", value: "abadan", selected: false },
    { id: 2, label: "بابل", value: "babol", selected: false },
    { id: 3, label: "بوشهر", value: "bushehr", selected: false },
    { id: 4, label: "تبریز", value: "tabriz", selected: false },
    { id: 5, label: "اراک", value: "arak", selected: false },
    { id: 6, label: "اصفهان", value: "isfahan", selected: false },
    { id: 7, label: "خراسان رضوی", value: "razavi_khorasan", selected: false },
    { id: 8, label: "خراسان شمالی", value: "north_khorasan", selected: false },
    { id: 9, label: "خراسان جنوبی", value: "south_khorasan", selected: false },
    { id: 10, label: "هرمزگان", value: "hormozgan", selected: false },
    { id: 11, label: "قم", value: "qom", selected: false },
    { id: 12, label: "ساری", value: "sari", selected: false },
    { id: 13, label: "سنندج", value: "sanandaj", selected: false },
    { id: 14, label: "گیلان", value: "guilan", selected: false },
    { id: 15, label: "گلستان", value: "golestan", selected: false },
    { id: 16, label: "مشهد", value: "mashhad", selected: false },
    { id: 17, label: "رشت", value: "rasht", selected: false },
    { id: 18, label: "قزوین", value: "qazvin", selected: false },
    { id: 19, label: "کرج", value: "karaj", selected: false },
    { id: 20, label: "کرمانشاه", value: "kermanshah", selected: false },
    { id: 21, label: "کرمان", value: "kerman", selected: false },
    { id: 22, label: "شیراز", value: "shiraz", selected: false },
    { id: 23, label: "اردبیل", value: "ardabil", selected: false },
    { id: 24, label: "ایلام", value: "ilam", selected: false },
    { id: 25, label: "یزد", value: "yazd", selected: false },
    { id: 26, label: "همدان", value: "hamedan", selected: false },
    { id: 27, label: "زنجان", value: "zanjan", selected: false },
    { id: 28, label: "زاهدان", value: "zahedan", selected: false },
    { id: 29, label: "لرستان", value: "lorestan", selected: false },
    { id: 30, label: "چهارمحال و بختیاری", value: "chaharmahal", selected: false },
    { id: 31, label: "تهران", value: "tehran", selected: false },
    { id: 32, label: "اهواز", value: "ahvaz", selected: false },
    { id: 33, label: "ارومیه", value: "urmia", selected: false },
    { id: 34, label: "بندرعباس", value: "bandar_abbas", selected: false },
    { id: 35, label: "خرم‌آباد", value: "khorramabad", selected: false },
    { id: 36, label: "گرگان", value: "gorgan", selected: false },
    { id: 37, label: "سمنان", value: "semnan", selected: false },
    { id: 38, label: "بیرجند", value: "birjand", selected: false },
    { id: 39, label: "بجنورد", value: "bojnurd", selected: false },
    { id: 40, label: "یاسوج", value: "yasuj", selected: false },
    { id: 41, label: "شهرکرد", value: "shahrekord", selected: false },
    { id: 42, label: "قائم‌شهر", value: "qaemshahr", selected: false },
    { id: 43, label: "آمل", value: "amol", selected: false },
    { id: 44, label: "کاشان", value: "kashan", selected: false },
    { id: 45, label: "نیشابور", value: "neyshabur", selected: false },
    { id: 46, label: "دزفول", value: "dezful", selected: false },
    { id: 47, label: "سبزوار", value: "sabzevar", selected: false },
    { id: 48, label: "گنبدکاووس", value: "gonbad", selected: false },
    { id: 49, label: "اسلامشهر", value: "eslamshahr", selected: false },
    { id: 50, label: "مرودشت", value: "marvdasht", selected: false },
    { id: 51, label: "بروجرد", value: "borujerd", selected: false },
    { id: 52, label: "سیرجان", value: "sirjan", selected: false },
    { id: 53, label: "اردکان", value: "ardakan", selected: false },
    { id: 54, label: "نجف‌آباد", value: "najafabad", selected: false },
    { id: 55, label: "لاهیجان", value: "lahijan", selected: false },
    { id: 56, label: "انزلی", value: "anzali", selected: false },
    { id: 57, label: "ملایر", value: "malayer", selected: false },
    { id: 58, label: "شاهرود", value: "shahroud", selected: false },
    { id: 59, label: "محمودآباد", value: "mahmudabad", selected: false },
    { id: 60, label: "مراغه", value: "maragheh", selected: false },
  ],
  districts: [
    { id: 1, label: "منطقه ۱", value: "district-1", selected: false },
    { id: 2, label: "منطقه ۲", value: "district-2", selected: false },
    { id: 3, label: "منطقه ۳", value: "district-3", selected: false },
    { id: 4, label: "منطقه ۴", value: "district-4", selected: false },
    { id: 5, label: "منطقه ۵", value: "district-5", selected: false },
    { id: 6, label: "منطقه ۶", value: "district-6", selected: false },
    { id: 7, label: "منطقه ۷", value: "district-7", selected: false },
    { id: 8, label: "منطقه ۸", value: "district-8", selected: false },
    { id: 9, label: "منطقه ۹", value: "district-9", selected: false },
    { id: 10, label: "منطقه ۱۰", value: "district-10", selected: false },
    { id: 11, label: "منطقه ۱۱", value: "district-11", selected: false },
    { id: 12, label: "منطقه ۱۲", value: "district-12", selected: false },
    { id: 13, label: "منطقه ۱۳", value: "district-13", selected: false },
    { id: 14, label: "منطقه ۱۴", value: "district-14", selected: false },
    { id: 15, label: "منطقه ۱۵", value: "district-15", selected: false },
    { id: 16, label: "منطقه ۱۶", value: "district-16", selected: false },
    { id: 17, label: "منطقه ۱۷", value: "district-17", selected: false },
    { id: 18, label: "منطقه ۱۸", value: "district-18", selected: false },
    { id: 19, label: "منطقه ۱۹", value: "district-19", selected: false },
    { id: 20, label: "منطقه ۲۰", value: "district-20", selected: false },
    { id: 21, label: "منطقه ۲۱", value: "district-21", selected: false },
    { id: 22, label: "منطقه ۲۲", value: "district-22", selected: false },
  ],
  propertyTypes: [
    { id: 1, label: "آپارتمان", value: "apartment", selected: false },
    { id: 2, label: "خانه ویلایی", value: "villa", selected: false },
    { id: 3, label: "خانه تک واحدی", value: "single_unit", selected: false },
    { id: 4, label: "پنت‌هاوس", value: "penthouse", selected: false },
    { id: 5, label: "مغازه/واحد تجاری", value: "commercial", selected: false },
    { id: 6, label: "دفتر اداری", value: "office", selected: false },
    { id: 7, label: "زمین", value: "land", selected: false },
    { id: 8, label: "ویلای باغ", value: "garden_villa", selected: false },
    { id: 9, label: "مزرعه/اراضی کشاورزی", value: "farm", selected: false },
  ],
};

// 🏠 Building systems and materials options
export const BUILDING_SYSTEMS_OPTIONS = {
  coolingSystem: [
    { id: 1, value: "any", label: "مهم نیست", selected: true },
    { id: 2, value: "water", label: "کولر آبی", selected: false },
    { id: 3, value: "split", label: "اسپلیت", selected: false },
    { id: 4, value: "fan", label: "فن کوئل", selected: false },
    { id: 5, value: "chiller", label: "چیلر", selected: false },
  ],
  heatingSystem: [
    { id: 1, value: "any", label: "مهم نیست", selected: true },
    { id: 2, value: "central", label: "مرکزی", selected: false },
    { id: 3, value: "split", label: "اسپلیت", selected: false },
    { id: 4, value: "fireplace", label: "شومینه", selected: false },
    { id: 5, value: "package", label: "پکیج", selected: false },
    { id: 6, value: "radiator", label: "رادیاتور", selected: false },
  ],
  floorMaterial: [
    { id: 1, value: "any", label: "مهم نیست", selected: true },
    { id: 2, value: "stone", label: "سنگ", selected: false },
    { id: 3, value: "ceramic", label: "سرامیک", selected: false },
    { id: 4, value: "parquet", label: "پارکت", selected: false },
    { id: 5, value: "laminate", label: "لمینت", selected: false },
    { id: 6, value: "mosaic", label: "موزاییک", selected: false },
  ],
};

// 🏷️ Labels for filter sections (displayed to user)
export const FILTER_LABELS = {
  district: "منطقه",
  propertyType: "نوع ملک",
  city: "شهر",
  coolingType: "سیستم سرمایشی",
  heatingType: "سیستم گرمایشی",
  floorType: "جنس کف",
};

// 🔢 Quantity-based filters configuration
export const AMENITIES_FILTER_CONFIG = [
  { id: 1, value: "bedrooms", label: "اتاق خواب" },
  { id: 2, value: "parking", label: "پارکینگ" },
  { id: 3, value: "storage", label: "انباری" },
  { id: 4, value: "elevator", label: "آسانسور" },
  { id: 5, value: "bathroom", label: "سرویس بهداشتی" },
  { id: 6, value: "bathroomType", label: "نوع سرویس بهداشتی" },
  { id: 7, value: "floor", label: "طبقه" },
];

// 📊 Visibility thresholds for filter groups
export const FILTER_VISIBILITY_RANGES = [
  {id:1, min: 0, max: 4, showLevel: 1 },
  {id:2, min: 4, max: 6, showLevel: 2 },
  {id:3, min: 6, max: AMENITIES_FILTER_CONFIG.length, showLevel: 3 },
];

// Define available filters for property features 🏠
export const PROPERTY_FILTERS = {
  bedrooms: [
    { id: 1, value: "any", label: "هر تعداد" },
    { id: 2, value: "0", label: "ندارد" },
    { id: 3, value: "1", label: "۱" },
    { id: 4, value: "2", label: "۲" },
    { id: 5, value: "3", label: "۳" },
    { id: 6, value: "4", label: "۴" },
    { id: 7, value: "5+", label: "+۵" },
  ],
  parking: [
    { id: 1, value: "any", label: "هر تعداد" },
    { id: 2, value: "0", label: "ندارد" },
    { id: 3, value: "1", label: "۱" },
    { id: 4, value: "2", label: "۲" },
    { id: 5, value: "3", label: "۳" },
    { id: 6, value: "4", label: "۴" },
    { id: 7, value: "5+", label: "+۵" },
  ],
  storage: [
    { id: 1, value: "any", label: "هر تعداد" },
    { id: 2, value: "0", label: "ندارد" },
    { id: 3, value: "1", label: "۱" },
    { id: 4, value: "2", label: "۲" },
    { id: 5, value: "3", label: "۳" },
    { id: 6, value: "4", label: "۴" },
    { id: 7, value: "5+", label: "+۵" },
  ],
  bathroom: [
    { id: 1, value: "any", label: "هر تعداد" },
    { id: 2, value: "1", label: "۱" },
    { id: 3, value: "2", label: "۲" },
    { id: 4, value: "3", label: "۳" },
    { id: 5, value: "4", label: "۴" },
    { id: 6, value: "5+", label: "+۵" },
  ],
  bathroomType: [
    { id: 1, value: "any", label: "مهم نیست" },
    { id: 2, value: "iranian", label: "ایرانی" },
    { id: 3, value: "foreign", label: "فرنگی" },
    { id: 4, value: "both", label: "هر دو" },
  ],
  elevator: [
    { id: 1, value: "any", label: "مهم نیست" },
    { id: 2, value: "1", label: "۱" },
    { id: 3, value: "2", label: "۲" },
    { id: 4, value: "3", label: "۳" },
    { id: 5, value: "4", label: "۴" },
    { id: 6, value: "5+", label: "+۵" },
  ],
  floor: [
    { id: 1, value: "any", label: "مهم نیست" },
    { id: 2, value: "0", label: "همکف" },
    { id: 3, value: "1", label: "۱" },
    { id: 4, value: "2", label: "۲" },
    { id: 5, value: "3", label: "۳" },
    { id: 6, value: "4", label: "۴" },
    { id: 7, value: "5+", label: "+۵" },
  ],
  coolingSystem: [
    { id: 1, value: "any", label: "مهم نیست" },
    { id: 2, value: "water", label: "کولر آبی" },
    { id: 3, value: "split", label: "اسپلیت" },
    { id: 4, value: "fan", label: "فن کوئل" },
    { id: 5, value: "chiller", label: "چیلر" },
  ],
  heatingSystem: [
    { id: 1, value: "any", label: "مهم نیست" },
    { id: 2, value: "central", label: "مرکزی" },
    { id: 3, value: "split", label: "اسپلیت" },
    { id: 4, value: "fireplace", label: "شومینه" },
    { id: 5, value: "package", label: "پکیج" },
    { id: 6, value: "radiator", label: "رادیاتور" },
  ],
  floorMaterial: [
    { id: 1, value: "any", label: "مهم نیست" },
    { id: 2, value: "stone", label: "سنگ" },
    { id: 3, value: "ceramic", label: "سرامیک" },
    { id: 4, value: "parquet", label: "پارکت" },
    { id: 5, value: "laminate", label: "لمینت" },
    { id: 6, value: "mosaic", label: "موزاییک" },
  ],
};

// Filter configuration for property features 🔧
export const FILTER_CONFIG = [
  {
    title: "اتاق خواب",
    name: "bedrooms",
    options: PROPERTY_FILTERS.bedrooms,
  },
  {
    title: "پارکینگ",
    name: "parking",
    options: PROPERTY_FILTERS.parking,
  },
  {
    title: "انباری",
    name: "storage",
    options: PROPERTY_FILTERS.storage,
  },
  {
    title: "سرویس بهداشتی",
    name: "bathroom",
    options: PROPERTY_FILTERS.bathroom,
  },
  {
    title: "نوع سرویس بهداشتی",
    name: "bathroomType",
    options: PROPERTY_FILTERS.bathroomType,
  },
  {
    title: "آسانسور",
    name: "elevator",
    options: PROPERTY_FILTERS.elevator,
  },
  {
    title: "طبقه",
    name: "floor",
    options: PROPERTY_FILTERS.floor,
  },
  {
    title: "سیستم سرمایش",
    name: "coolingSystem",
    options: PROPERTY_FILTERS.coolingSystem,
  },
  {
    title: "سیستم گرمایش",
    name: "heatingSystem",
    options: PROPERTY_FILTERS.heatingSystem,
  },
  {
    title: "جنس کف",
    name: "floorMaterial",
    options: PROPERTY_FILTERS.floorMaterial,
  },
];

// List of keys to remove from the filter 🗑️
export const keysToRemove = [
  "cooling-system",
  "heating-system",
  "floor-material",
  "bedrooms",
  "parking",
  "storage",
  "elevator",
  "bathroom",
  "bathroom-type",
  "floor",
  "min-price",
  "max-price",
  "areas",
  "min-size",
  "max-size",
  "property-type",
];

// Allowed keys for filtering ✅
export const allowedKeys = [
  "bedrooms",
  "parking",
  "storage",
  "bathroom",
  "bathroom-type",
  "elevator",
  "floor",
  "cooling-system",
  "heating-system",
  "floor-material",
];

